# GitHub Funding Configuration
# This file configures the "Sponsor" button on your repository.
# Documentation: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors username
github: [yooakim]

# Patreon username
# patreon:

# Open Collective username
# open_collective:

# Ko-fi username
# ko_fi:

# Tidelift package name (format: platform-name/package-name)
# tidelift:

# Community Bridge project name
# community_bridge:

# Liberapay username
# liberapay:

# IssueHunt username
# issuehunt:

# Otechie username
# otechie:

# LFX Crowdfunding project name
# lfx_crowdfunding:

# Custom sponsorship URLs (up to 4)
# custom: ['https://www.example.com/sponsor']
