name: Bug Report
description: Report a bug or unexpected behavior in Seq.App.SftpCheck
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - yooakim

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Configure app with...
        2. Set the following settings...
        3. Wait for check to run...
        4. See error...
    validations:
      required: true

  - type: dropdown
    id: authentication
    attributes:
      label: Authentication Method
      description: Which authentication method are you using?
      options:
        - Password
        - Private Key
        - Both (multiple instances)
    validations:
      required: true

  - type: input
    id: seq-version
    attributes:
      label: Seq Version
      description: What version of Seq are you running?
      placeholder: "e.g., 2024.1"
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of Seq.App.SftpCheck are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Seq Deployment Type
      description: How is Seq deployed?
      options:
        - Docker
        - Windows Service
        - Kubernetes
        - Other
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: App Configuration
      description: |
        Please provide the app instance configuration (redact sensitive information like passwords and private keys).
      placeholder: |
        Host: sftp.example.com
        Port: 22
        Username: myuser
        Authentication Method: Password
        Check Interval: 300
        Connection Timeout: 30
        Test Directory Path: /uploads
      render: yaml
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: |
        Please paste any relevant log entries from Seq. You can filter by `SftpHost is not null` to find related events.
      render: text
    validations:
      required: false

  - type: textarea
    id: sftp-server
    attributes:
      label: SFTP Server Information
      description: |
        If known, provide information about the SFTP server (software, version, OS).
      placeholder: |
        Server: OpenSSH 8.9
        OS: Ubuntu 22.04
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem here.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues to ensure this bug hasn't already been reported.
          required: true
        - label: I have tested connectivity to the SFTP server using another tool (e.g., sftp command, WinSCP).
          required: false
        - label: I have verified my credentials are correct.
          required: false
