name: Feature Request
description: Suggest a new feature or enhancement for Seq.App.SftpCheck
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - yooakim

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the information below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like the app to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I also considered...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of the app does this feature relate to?
      options:
        - Authentication (password, private key, etc.)
        - Connectivity checks
        - Logging and events
        - Configuration and settings
        - Performance
        - Security
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would help.
      placeholder: |
        In my environment, I need to...
        This feature would help because...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: |
        If applicable, provide examples of how the feature might work.
        This could include configuration examples, log output examples, or UI mockups.
      placeholder: |
        Example configuration:
        ```yaml
        Host: sftp.example.com
        NewSetting: value
        ```
      render: markdown
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to submit a pull request for this feature.
          required: false
        - label: I would be willing to help test this feature.
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues to ensure this feature hasn't already been requested.
          required: true
        - label: I have checked the README and documentation to confirm this feature doesn't already exist.
          required: true
